from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer
)

from reportlab.lib.styles import (
    getSampleStyleSheet,
    ParagraphStyle
)

from reportlab.lib.enums import TA_CENTER
from reportlab.lib import colors

from datetime import datetime

import os
import re


def clean_content(content):

    content = re.sub(r"\*\*", "", content)
    content = re.sub(r"###", "", content)
    content = re.sub(r"##", "", content)
    content = re.sub(r"#", "", content)
    content = re.sub(r"---+", "", content)

    return content


def generate_pdf(
    content,
    report_type,
    folder,
    topic="Report"
):

    content = clean_content(content)

    os.makedirs(folder, exist_ok=True)

    timestamp = datetime.now().strftime(
        "%Y%m%d_%H%M%S"
    )

    safe_topic = (
        topic.replace(" ", "_")
        .replace("/", "_")
        .replace("\\", "_")
    )

    filename = (
        f"{report_type}_{safe_topic}_{timestamp}.pdf"
    )

    filepath = os.path.join(
        folder,
        filename
    )

    doc = SimpleDocTemplate(
        filepath,
        rightMargin=40,
        leftMargin=40,
        topMargin=50,
        bottomMargin=40
    )

    styles = getSampleStyleSheet()

    title_style = ParagraphStyle(
        "Title",
        parent=styles["Title"],
        alignment=TA_CENTER,
        fontSize=24,
        textColor=colors.HexColor(
            "#0F766E"
        )
    )

    subtitle_style = ParagraphStyle(
        "Subtitle",
        parent=styles["Heading2"],
        alignment=TA_CENTER
    )

    heading_style = ParagraphStyle(
        "Heading",
        parent=styles["Heading2"],
        textColor=colors.HexColor(
            "#0F766E"
        )
    )

    body_style = ParagraphStyle(
        "Body",
        parent=styles["BodyText"],
        fontSize=11,
        leading=18
    )

    story = []

    story.append(
        Paragraph(
            "LUMORA AI",
            title_style
        )
    )

    story.append(
        Paragraph(
            "Academic Intelligence Platform",
            subtitle_style
        )
    )

    story.append(
        Spacer(1, 20)
    )

    story.append(
        Paragraph(
            report_type,
            heading_style
        )
    )

    story.append(
        Paragraph(
            f"Generated On: {datetime.now().strftime('%d %B %Y %H:%M')}",
            body_style
        )
    )

    story.append(
        Spacer(1, 20)
    )

    lines = content.split("\n")

    for line in lines:

        line = line.strip()

        if not line:
            continue

        if (
            "QUESTION" in line.upper()
            or "ANSWER" in line.upper()
            or "SECTION" in line.upper()
        ):

            story.append(
                Paragraph(
                    f"<b>{line}</b>",
                    heading_style
                )
            )

        else:

            story.append(
                Paragraph(
                    line,
                    body_style
                )
            )

        story.append(
            Spacer(1, 5)
        )

    story.append(
        Spacer(1, 20)
    )

    story.append(
        Paragraph(
            "Generated by Lumora AI",
            subtitle_style
        )
    )

    doc.build(story)

    return filepath